mulchmen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from appointments import views
from accounts import views as accounts_views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('about/', views.about, name='about'),
    path('orders/', views.orders, name='profile'),
    path('thankyou/', views.thankyou, name='thankyou'),
    path('money/', views.money, name='money'),


    path('settings/account/', accounts_views.UserUpdateView.as_view(), name='edit_account'),
    path('contact/', views.contact, name='contact'),
    path('social-auth/', include('social_django.urls', namespace="social")),

    path('schedule/', views.schedule, name='schedule'),
    path('staff_schedule/', views.schedule_staff, name='schedule_staff'),
    path('appointments/', views.view_appointments, name='view_appointments'),
    path('appointments/<int:pk>/edit/', views.AppointmentUpdateView.as_view(), name='edit_appointment'),
    path('appointments/<int:pk>/view/', views.AppointmentDetailView.as_view(), name='view_appointment'),
    path('appointments/<int:pk>/confirm/', views.confirm_appointment, name='confirm_appointment'),
    path('appointments/<int:pk>/complete/', views.complete_appointment, name='complete_appointment'),
    path('appointments/<int:pk>/remove/', views.AppointmentDeleteView.as_view(), name='appointment_remove'),

    path('expenses/', views.view_expenses, name='view_expenses'),
    path('expenses/<int:pk>/edit/', views.ExpenseUpdateView.as_view(), name='edit_expense'),
    path('expenses/<int:pk>/view/', views.ExpenseDetailView.as_view(), name='view_expense'),
    path('expenses/new/', views.new_expense, name='new_expense'),
    path('expenses/<int:pk>/pay/', views.pay_expense, name='pay_expense'),
    path('expenses/<int:pk>/remove/', views.ExpenseDeleteView.as_view(), name='expense_remove'),





    path('signup/', accounts_views.signup, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name="login"),

    path('settings/account/', accounts_views.UserUpdateView.as_view(), name='my_account'),


    path('reset/',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt'
            ),
            name='password_reset'),
    path('reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('reset/complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),

    path('settings/password/', auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
        name='password_change'),
    path('settings/password/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
        name='password_change_done'),
]

appointments/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField


class Appointment(models.Model):
    STATUS_CHOICES = [('P', 'Pending'), ('S', 'Scheduled'), ('C', 'Completed')]
    DELIVERY_CHOICES = [('P', 'I will set up the mulch delivery'), ('M', 'I would like MulchMen to set up the mulch delivery')]
    name = models.CharField(max_length=50, blank=False)
    email = models.EmailField(max_length=254, blank=True)
    phone = PhoneNumberField(region='US', blank=True, help_text="Not required")
    address = models.CharField(max_length=50,  blank=False)
    cubic_yards = models.PositiveIntegerField(blank=False, help_text="$25-35/cu. yard")
    weeding = models.BooleanField(blank=False, help_text="$5/cu. yard")
    bed_cleaning = models.BooleanField(blank=False, help_text="$5/cu. yard", default=False)
    edging = models.BooleanField(blank=False, help_text="$0.60/foot")
    delivery = models.CharField(max_length=1, choices=DELIVERY_CHOICES, default='P')
    date = models.DateField(auto_now=False, auto_now_add=False)
    status = models.CharField(default='P', max_length=1, choices=STATUS_CHOICES)
    cost = models.DecimalField(default=0, max_digits=16, decimal_places=2)
    sumbitted_at = models.DateTimeField(auto_now_add=True)
    hear_about_us = models.CharField(max_length=100, help_text="Facebook, reference, etc")
    additional_comments = models.CharField(max_length=2000, blank=True, help_text="Type of mulch, delivery instructions, quantity of mulch confusion, special requests, etc")

    user = models.ForeignKey(User, related_name='appointments', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name



class Expense(models.Model):
    expense = models.CharField(max_length=50, blank=False)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    purchaser = models.CharField(max_length=50, blank=False)
    paid = models.BooleanField(blank=False, default=False)

    def __str__(self):
        return self.expense

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}MulchMen{% endblock %}</title>
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="favicon.ico" />  
  <link href="https://fonts.googleapis.com/css2?family=Baloo+Bhaina+2&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
  <link rel="stylesheet" href="{% static 'css/hor_scroll.css' %}">
  <link rel="stylesheet" href="{% static 'css/logo_adjust.css' %}">
  {% block stylesheet %}{% endblock %}
  
 </head>

<body>
  {% block page %}
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'images/logo.png' %}" width="150" height="36" alt="MulchMen">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu"
        aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% if user.is_staff %}
      <div class="collapse navbar-collapse" id="mainMenu">
        <div class="navbar-nav">
          <a class="nav-item nav-link" href="{% url 'view_appointments' %}">Appointments</a>
          <a class="nav-item nav-link" href="{% url 'view_expenses' %}">Expenses</a>
          <a class="nav-item nav-link" href="{% url 'money' %}">Money Breakdown</a>

        </div>
      {% else %}
        <div class="collapse navbar-collapse" id="mainMenu">
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'schedule' %}">Schedule</a>
            <a class="nav-item nav-link" href="{% url 'contact' %}">Contact Us</a>
            <a class="nav-item nav-link" href="{% url 'profile' %}">Your Orders</a>
          </div>
      {% endif %}
          <div class="collapse navbar-collapse" id="mainMenu">
            {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true"
                  aria-expanded="false">
                  {{ user.first_name }} {{ user.last_name }}
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                  <a class="dropdown-item" href="{% url 'edit_account' %}">My account</a>
                  <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                </div>
              </li>
            </ul>
            {% else %}
            <form class="form-inline ml-auto">
              <a href="{% url 'signup' %}" class="btn btn-success">Sign up</a>
              <a href="{% url 'login' %}" class="btn btn-outline-success ml-2">Login</a>
            </form>
            {% endif %}
          </div>
        </div>
      </div>
  </nav>


  {% block body_no_container %}


  <div class="container">
  {% block body %}
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb my-4">
        {% block breadcrumb %}
        {% endblock %}
      </ol>
    </nav>


      {% block content %}
      {% endblock %}
  </div>

    {% endblock body %}
{% endblock body_no_container%}

  {% endblock page %}



  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

  {% block javascript %}{% endblock %}

</body>

</html>

templates/base_accounts.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
  <link rel="stylesheet" href="{% static 'css/facebook.css' %}">
  <link rel="stylesheet" href="{% static 'css/logo_adjust.css' %}">
{% endblock %}

{% block page %}
  <div class="container header-logo">
    <h1 class="text-center logo my-4">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'images/logo.png' %}" alt="">
      </a>
    </h1>




    {% block content %}
    {% endblock %}
  </div>
{% endblock %}

templates/edit_account.html
{% extends 'base.html' %}

{% block title %}My account{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">My account</li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Save changes</button>
      </form>
    </div>
  </div>
{% endblock %}

templates/edit_appointment.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Edit Appointment{% endblock %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/simplemde.min.css' %}">
{% endblock %}

{% block javascript %}
  <script src="{% static 'js/simplemde.min.js' %}"></script>
  <script>
    var simplemde = new SimpleMDE();
  </script>
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'view_appointments' %}">Appointments</a></li>
  <li class="breadcrumb-item">Edit {{ appointment.name }}'s Appointment</a></li>
{% endblock %}

{% block content %}
  <form method="post" class="mb-4" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success mr-2">Save changes</button>
    <a href="{% url 'view_appointments' %}" class="btn btn-outline-secondary" role="button">Cancel</a>
  </form>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% load static %}


{% block stylesheet%}
<link href="{% static 'css/carousel.css' %}" rel="stylesheet">
<link href="{% static 'css/pricing.css' %}" rel="stylesheet">
<link href="{% static 'css/photo_no_stretch.css' %}" rel="stylesheet">

{% endblock %}

{% block body_no_container %}
       <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="first-slide photo" src="{% static 'images/mulch4.JPG' %}" alt="First slide">
            <div class="container">
              <!-- <div class="carousel-caption text-left">
                <h1>Example headline.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
              </div> -->
            </div>
          </div>
          <div class="carousel-item">
            <img class="second-slide photo" src="{% static 'images/mulch2.JPG' %}" alt="Second slide">
            <div class="container">
              <!-- <div class="carousel-caption">
                <h1>Another example headline.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
              </div> -->
            </div>
          </div>
          <div class="carousel-item">
            <img class="third-slide photo" src="{% static 'images/mulch3.JPG' %}" alt="Third slide">
            <div class="container">
              <!-- <div class="carousel-caption text-right">
                <h1>One more for good measure.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
              </div> -->
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div> 



<!-- PRICING -->

<div class="pricing-header px-3 py-3 pt-md-1 pb-md-4 mx-auto text-center">
    <h1 class="display-4 mb-1">Pricing</h1>
      <p class="lead">Affordable pricing with great results!</p>
      <a href="{% url 'schedule' %}" class="btn btn-lg btn-outline-success">Schedule</a>

    </div>

    <div class="container">
      <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Spreading</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$25-35 <small class="text-muted">/ cubic yard</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>1-3 cubic yards : $35/cu. yard</li>
              <li>4-8 cubic yards : $30/cu. yard</li>
              <li>9+  cubic yards : $25/cu. yard</li>
            </ul>
          </div>
        </div>
        <div class="card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Edging</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$0.60 <small class="text-muted">/ foot</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>We create or redefine an edge around your beds. This will make your yard stand out amongst those competitive neighbors of yours</li>
            </ul>
          </div>
        </div>
        <div class="card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Weeding</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$5 <small class="text-muted">/ cubic yard</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>We pull all the weeds and spray the beds with a weed killer to prevent future growth</li>
            </ul>
          </div>
        </div>
      </div>




<!-- Profile cards -->
    <div class="pricing-header px-3 py-3 pt-md-1 pb-md-4 mx-auto text-center">
      <h1 class="display-4 mt-4">About Us</h1>
      <p class="lead">We are all Strongsville High School graduates and are currently sophmores in college. We love being active and spending time outdoors. Passionate about our new business, we look forward to transforming your yard. </p>
     <a href="{% url 'contact' %}" class="btn btn-lg btn-outline-success">Contact Us</a>
    </div>


      <div class="container marketing">
        <div class="row">
          <div class="col-lg-4">
            <img class="rounded-circle mb-2" src="{% static 'images/connor.jpg'%}" alt="Generic placeholder image" width="140" height="140">
            <h2>Connor Bowman</h2>
            <p>Connor is a student-athlete at William and Mary majoring in Computer Science and Business Analytics.</p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="rounded-circle mb-2" src="{% static 'images/jack.png'%}" alt="Generic placeholder image" width="140" height="140">
            <h2>Jack Mott</h2>
            <p>Jack is at The Ohio State University majoring in Finance and minoring in Computer Information Systems.</p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="rounded-circle mb-2" src="{% static 'images/aske.png'%}" alt="Generic placeholder image" width="140" height="140">
            <h2>Andrew Aske</h2>
            <p>Andrew is at The University of Cincinnati majoring in Computer Science Engineering.</p>
          </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->









{% endblock %}

templates/login.html
{% extends 'base_accounts.html' %}

{% load static %}
{% block title %}Login to MulchMen{% endblock %}


{% block content %}

{% comment %}
     <div class="row">
      <div class="col text-center">
          <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}"  class="fb connect mb-3">Login with Facebook</a>
          <p class="mb-3">or</p> 
      </div>
    </div>
  </div>
{% endcomment %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8 ml-4 mr-4">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Log in</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Log in</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
          New to MulchMen? <a href="{% url 'signup' %}">Sign up</a>
        </div>
      </div>
      <div class="text-center py-2 mb-4">
        <small>
          <a href="{% url 'password_reset' %}" class="text-muted">Forgot your password?</a>
        </small>
      </div>
    </div>
  </div>

{% endblock %}

templates/new_expense.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}New Expense{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item">Add a New Expense</li>
{% endblock %}

{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success mb-4">Submit</button>
  </form>
{% endblock %}

templates/password_change.html
{% extends 'base.html' %}

{% block title %}Change password{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Change password</li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10 ml-4 mr-4">
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Change password</button>
      </form>
    </div>
  </div>
{% endblock %}

templates/password_reset.html
{% extends 'base_accounts.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8 ml-4 mr-4">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Enter your email address and we will send you a link to reset your password.</p>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/password_reset_done.html
{% extends 'base_accounts.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8 ml-4 mr-4">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Check your email for a link to reset your password. If it doesn't appear within a few minutes, check your spam folder.</p>
          <a href="{% url 'login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/schedule.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% load static %}
{% block title %}Schedule a New Appointment{% endblock %}


{% block breadcrumb %}
  <li class="breadcrumb-item">Schedule a New Appointment</li>
{% endblock %}

{% block content %}


  <form method="post" style="text-align: left"  novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success mb-4">Submit</button>
  </form>

{% endblock %}

templates/signup.html
{% extends 'base_accounts.html' %}

{% block title %}Sign up to MulchMen{% endblock %}

{% block content %}
{% comment %} 
    <div class="row">
      <div class="col text-center">
          <a href="{% url 'social:begin' 'facebook' %}{% if request.GET.next %}?next={{ request.GET.next }}{% endif %}" class="fb connect mb-3">Continue with Facebook</a>
          <p class="mb-3">or</p> 
      </div>
    </div>
  </div> {% endcomment %}

  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12 ml-4 mr-4 mb-4">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Sign up</h3>
          <div class="container">
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block mb-3">Create an account</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
          Already have an account? <a href="{% url 'login' %}">Log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/thankyou.html
{% extends 'base.html' %}

{% load to_string %}


{% load static %}

{% block title %}Thank you!{% endblock %}


{% block stylesheet%}
<link href="{% static 'css/carousel.css' %}" rel="stylesheet">
{% endblock %}

{% block body %}


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-3">Thank you for choosing MulchMen!</h1>
  {% comment %} <h2 class="display-4">Your Orders</h2> {% endcomment %}
  <p>Check your inbox for a confirmation email that we received your order. We will contact you soon to confirm your appointment. Contact us with any further questions and we cannot wait to help transform your yard!</p>
</div>


  {% endblock %}

templates/view_appointment.html
{% extends 'base.html' %}

{% load static %}

{% block title %}View Appointment{% endblock %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/simplemde.min.css' %}">
  
{% endblock %}

{% block javascript %}
  <script src="{% static 'js/simplemde.min.js' %}"></script>
  <script>
    var simplemde = new SimpleMDE();
  </script>
{% endblock %}


{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'view_appointments' %}">Appointments</a></li>
  <li class="breadcrumb-item">View {{ appointment.name }}'s Appointment</a></li>
{% endblock %}

{% block content %}


<dl class="row ">
  <dt class="col-sm-3">Name</dt>
  <dd class="col-sm-9">{{ appointment.name }}</dd>

  <dt class="col-sm-3">Email</dt>
  <dd class="col-sm-9">{{ appointment.email }}</dd>
  
  <dt class="col-sm-3">Phone</dt>
  <dd class="col-sm-9">{{ appointment.phone }}</dd>

  <dt class="col-sm-3">Address</dt>
  <dd class="col-sm-9">{{ appointment.address }}</dd>

  <dt class="col-sm-3">Cubic Yards</dt>
  <dd class="col-sm-9">{{ appointment.cubic_yards }}</dd>

  <dt class="col-sm-3">Weeding</dt>
  <dd class="col-sm-9">{% if appointment.weeding is True %}Weeding{% else %}No Weeding{% endif %}</dd>

  <dt class="col-sm-3">Bed Cleaning</dt>
  <dd class="col-sm-9">{% if appointment.bed_cleaning is True %}Bed Cleaning{% else %}No Bed Cleaning{% endif %}</dd>

  <dt class="col-sm-3">Edging</dt>
  <dd class="col-sm-9">{% if appointment.edging is True %}Edging{% else %}No Edging{% endif %}</dd>

  <dt class="col-sm-3">Delivery</dt>
  <dd class="col-sm-9">{{ appointment.get_delivery_display }}</dd>

  <dt class="col-sm-3">Date</dt>
  <dd class="col-sm-9">{{ appointment.date }}</dd>

  <dt class="col-sm-3">Status</dt>
  <dd class="col-sm-9">{{ appointment.get_status_display }}</dd>

  <dt class="col-sm-3">Cost</dt>
  <dd class="col-sm-9">{{ appointment.cost }}</dd>

  <dt class="col-sm-3">Hear About Us</dt>
  <dd class="col-sm-9">{{ appointment.hear_about_us }}</dd>

  <dt class="col-sm-3">Comments</dt>
  <dd class="col-sm-9">{{ appointment.additional_comments }}</dd>  
</dl>

<a href="{% url 'edit_appointment' appointment.pk %}" class="btn btn-outline-primary mr-2 mb-2">Edit</a>

{% if appointment.get_status_display == 'Pending' %}
<a href="{% url 'confirm_appointment' appointment.pk %}" class="btn btn-primary mb-2">Confirm</a>
{% elif appointment.get_status_display == 'Scheduled' %}
<a href="{% url 'complete_appointment' appointment.pk %}" class="btn btn-success mb-2">Complete</a>
{% endif %}


<button class="btn btn-danger float-right" data-toggle="modal" data-target="#fm-modal-grid">Delete</button>
<div class="modal fade" id="fm-modal-grid" tabindex="-1" role="dialog" aria-labelledBy="fm-modal-grid"
  aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">Delete Appointment</h5>
        <button class="close" data-dismiss="modal" aria-label="Cerrar">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container-fluid">
          <div class="row">
            <div class="col-12 col-sm-6">
              <p>Are you sure you want to delete {{ appointment.name }}'s apppointment?</p>
            </div>
          </div>
        </div>
      </div>

      <div class="modal-footer">
        <form action="{% url 'appointment_remove' pk=appointment.pk %}" method="POST">
          {% csrf_token %}
          <button class="btn btn-outline-danger">Delete</button>
        </form>
        <button class="btn btn-primary" data-dismiss="modal">Cancel</button>

      </div>
    </div>
  </div>
</div>

{% endblock %}